name: 'UploadWebsiteFiles'

# The workflow should only trigger on push events to the main branch
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . ${{ secrets.S3_BUCKET_URI }}

    - name: Invalidate cloudfront cache
      run : |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.ROOT_DOMAIN_DISTRIBUTION_ID }} --paths "/*"
        aws cloudfront create-invalidation --distribution-id ${{ secrets.SUB_DOMAIN_DISTRIBUTION_ID }} --paths "/*"
